services:
  - type: web
    name: orbit
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn orbit.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.11.0
